GO
USE Northwind
GO
--VISUALIZAR TABLAS
GO
SELECT * FROM Categories
GO
SELECT * FROM Customers
GO
SELECT * FROM Employees
GO
SELECT * FROM EmployeeTerritories
GO
SELECT * FROM [Order Details]
GO
SELECT * FROM Orders
GO
SELECT * FROM Products
GO
SELECT * FROM Region
GO
SELECT * FROM Shippers
GO
--CONSULTAS CON ALIAS
GO
SELECT * FROM Customers
GO
SELECT CustomerID AS CODIGO,ContactName 
[NOMBRE CONTACTO], City "CIUDAD" FROM Customers

--CONSULTAS CONDICIONALES:
/*
CLAUSULA WHERE: QUE

OPERADORES: 
CLAUSULA WHERE:

OPERADOR COMPARACIÓN: BOOLEAN(F/V)
*/
--EJEMPLO
--LISTAR TODOS LOS CONTACTOS DE CLIENTE QUE RESIDEN
--EN LA CIUDAD MADRID
GO
SELECT * FROM Customers WHERE city = 'MADRID'
GO
--LISTAR LOS PRECIOS DE PRODUCTOS MAYORES A 80
SELECT * FROM Products WHERE UnitPrice > 80 ORDER BY UnitPrice 

--VALORES LÓGICOS (AND/OR/NOT):
GO
SELECT * FROM Products WHERE UnitPrice >18 AND ProductName='CHANG'
GO
SELECT * FROM Products WHERE UnitPrice >18 OR ProductName='CHANG'
GO
SELECT * FROM Products WHERE UnitPrice >18 AND NOT ProductName='CHANG'

--VALORES DE INTERVALO: BETWEEN
GO
--LISTAR TODOS LOS PRODUCTOS CUYO PRECIO SE ENCUENTRE ENTRE 70 A 300
SELECT ProductID, ProductName, UnitPrice FROM Products WHERE UnitPrice BETWEEN 70 AND 300

--LISTA DE VALORES: IN / NOT IN
SELECT Country FROM Customers WHERE Country 
IN ('ITALY', 'BRAZIL','SPAIN')

SELECT Country FROM Customers WHERE Country 
NOT IN ('ITALY', 'BRAZIL','SPAIN')

--COINCIDENCIA DE PATRONES
/*
% <---- CUALQUIER CARACTER DE CERO A MÁS
_ <---- CUALQUIER CARACTER
[F-J] <---- CUALQUIER CARACTER INDIVIDUAL DENTRO DEL INTERVALO
^[F-J]
*/

GO
SELECT * FROM Employees
GO
--LISTAR A LOS EMPLEADOS CUYA INICIAL DE SU NOMBRE SEA
SELECT EmployeeID,FirstName FROM Employees WHERE FirstName LIKE 'A%'
GO
SELECT EmployeeID,FirstName FROM Employees WHERE FirstName LIKE '_N%'
GO
SELECT CustomerID,CompanyName FROM Customers WHERE CompanyName LIKE '[C-D]%'
GO
SELECT CustomerID,CompanyName FROM Customers WHERE CompanyName LIKE '^[C-D]%'
GO
--FUNCIONES DE SQL
GO
--SPACE: ESPACIOS
GO
SELECT ('SENATI')+SPACE(1)+('INTELIGENCIA ARTIFICIAL')
GO
--REPLACE: REEMPLAZAR
GO
SELECT REPLACE('ALL FUNCTION','ALL','SQL')
GO
--STUFF: INSERTA UNA CADENA SOBRE UN ÍNDICE DE ESP.ESPECIFICO
GO
SELECT STUFF('SQLTUTORIAL',4,6,'FUNCTION')
GO
--LEFT: IZQUIERDA
GO
SELECT LEFT('INTELIGENCIA ARTIFICIAL',4)
GO
--RIGHT: DERECHA
SELECT RIGHT('INTELIGENCIA ARTIFICIAL',4)
GO
--REPLICATE
SELECT REPLICATE('SENATI'+SPACE(12),5)
GO
--SUBSTRING
SELECT SUBSTRING('SQL SERVER',4,3)
GO
--LEN
SELECT LEN('SENATI')
GO
--REVERSE
GO
SELECT REVERSE('SENATI')
GO
--LOWER
SELECT LOWER('SENATI')
GO
--UPPER
SELECT UPPER('senati')
GO
--LTRIM
SELECT LTRIM('     BASE DATOS')